version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.2
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Install dependent npm packages
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm test
